
  services:

    mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - "27017:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
      volumes:
        - ./data/mongo/booking:/data/db  # Persistent storage for MongoDB
        - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js/booking-init.js:/docker-entrypoint-initdb.d/booking-init.js
      networks:
        - spring

    mongo-express:
      image: mongo-express
      ports:
        - "8081:8081"
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_SERVER=mongodb
      container_name: mongo-express
      depends_on:
        - mongodb
      networks:
        - spring
  networks:
    spring:
      driver: bridge
  volumes:
    mongo-db:
      driver: local
