
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb-event
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/event:/data/db  # Persistent storage for MongoDB
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js/event-init.js:/docker-entrypoint-initdb.d/event-init.js
    networks:
      - spring


  mongo-express:
    image: mongo-express
    ports:
      - "8082:8082"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-event
    container_name: mongo-express-event
    depends_on:
      - mongodb
    networks:
      - spring
networks:
  spring:
    external: true

volumes:
  mongo-db:
    driver: local

