
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb-approval
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/booking:/data/db  # Persistent storage for MongoDB
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js/approval-init.js:/docker-entrypoint-initdb.d/approval-init.js
    networks:
      - spring

  mongo-express:
    image: mongo-express
    ports:
      - "8083:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-approval
    container_name: mongo-express-approval
    depends_on:
      - mongodb
    networks:
      - spring
networks:
  spring:
    driver: bridge
volumes:
  mongo-db:
    driver: local
