services:

  postgres-user:
    image: postgres:latest
    container_name: postgres-user
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user_service
    volumes:
      - ./data/postgres/user:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data
      - ./init/postgres/user-init.sql:/docker-entrypoint-initdb.d/user-init.sql  # Initialization script
    networks:
      - spring

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-user
    ports:
      - "8085:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - spring

networks:
  spring:
    driver: bridge

volumes:
  postgres-user-db:
    driver: local
